import React from "react";

export const metadata = {
  title: "SubDomainLayout",
  description: "Generated by create next app",
};
const SubDomainLayout = ({ children }) => {
  return (
    <React.Fragment>
      <div>{children}</div>
    </React.Fragment>
  );
};

export default SubDomainLayout;
